version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: altair_bd
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    expose:
      - 27018
    command: --quiet

  mongo-express:
    image: mongo-express
    container_name: mongo-express-altair
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=altair_bd
    depends_on:
      - mongodb
#  web:
#    build:
#        context: .
#    command: python3 manage.py runserver
#    ports:
#      - 8000:8000
#    depends_on:
#      - mongodb

networks:
  default:
    name: mongodb_network_altair