name: DEV (pullrequest) - Build

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.10.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        sudo apt-get install -y default-jre
        sudo apt-get install -y libpangocairo-1.0-0
        python -m pip install --upgrade pip setuptools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8 # this will check the python code for syntax errors/editing errors
      run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Tests
      run: |
          python manage.py test